layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: justin-helfman-2b21a0168
  email: 
  #Resume:

languages:
  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/c/c.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
    
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

topics:
  - name: Machine and Deep Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://cdn.pixabay.com/photo/2017/09/08/19/07/a-2729794_1280.png

  - name: Algorithms
    web_url: https://github.com/topics/algorithm
    image_url: https://thumbs.dreamstime.com/b/programing-workflow-abstract-algorithm-programing-workflow-abstract-algorithm-concept-124110762.jpg

  - name: Continious Integration
    web_url: https://github.com/topics/continuous-integration
    image_url: https://cdn.pixabay.com/photo/2018/02/20/19/02/isolated-3168537__340.png

tolearn:
  - name: Project Management
    web_url: https://github.com/topics/project-management
    image_url: https://cdn.pixabay.com/photo/2017/02/13/02/17/project-management-2061635_1280.jpg
  
  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
      
  - name: Unity
    web_url: https://github.com/topics/unity
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/unity/unity.png
  
