layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
     - jbhelf.github.io

social_media:
  linkedin: justin-helfman-2b21a0168
  email: ''
  resume: Justin%20Helfman%20-%20Resume.pdf

languages:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/c/c.png
    
  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bash/bash.png

topics:
  - name: Machine and Deep Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://cdn.pixabay.com/photo/2017/09/08/19/07/a-2729794_1280.png

  - name: DevOps
    web_url: https://www.redhat.com/en/topics/devops
    image_url: https://miro.medium.com/max/716/1*ktxaMApynOG3_tcqImzhYA.png

  - name: Software Engineering
    web_url: https://www.guru99.com/what-is-software-engineering
    image_url: https://www.concordia.ca/content/concordia/en/academics/graduate/software-engineering-meng.img.png/1601320880626.jpg
  
  

#topics:
#  - name: DevOps
#    web_url: https://www.redhat.com/en/topics/devops
#    image_url: https://devopedia.org/images/article/54/7602.1513404277.png
  
#  - name: Software Engineering
#    web_url: https://www.guru99.com/what-is-software-engineering.html
#    image_url: https://www.guru99.com/images/1/093019_0641_WhatisSoftw1.png
  
#    - name: Machine and Deep Learning
#    web_url: https://github.com/topics/machine-learning
#    image_url: https://cdn.pixabay.com/photo/2017/09/08/19/07/a-2729794_1280.png

#tolearn:
#  - name: Project Management
#    web_url: https://github.com/topics/project-management
#    image_url: https://cdn.pixabay.com/photo/2017/02/13/02/17/project-management-2061635_1280.jpg
  
#  - name: Amazon Web Services
#    web_url: https://github.com/topics/aws
#    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
      
#  - name: Unity
#    web_url: https://github.com/topics/unity
#    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/unity/unity.png
  
