layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
     - jbhelf.github.io

social_media:
  linkedin: justin-helfman-2b21a0168
  email: ''
  resume: Justin%20Helfman%20-%20Resume.pdf

languages:
  - name: Python & Django
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Cloud Infrastructure (AWS, GCP, Azure)
    web_url: https://aws.amazon.com/what-is-cloud-computing/
    image_url: https://static.vecteezy.com/system/resources/previews/024/560/649/non_2x/cloud-computing-icon-free-png.png
    
  - name: Bash & Linux
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bash/bash.png

topics:
  - name: Sales & Solutions Engineering
    web_url: https://sales-engineering.org/
    image_url: https://miro.medium.com/v2/resize:fit:1400/0*aFN9idLLBlRkbPVN.png

  - name: DevOps & Site Reliability
    web_url: https://aws.amazon.com/devops/what-is-devops/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Devops-toolchain.svg/2560px-Devops-toolchain.svg.png

  - name: AI for Everyday Tools
    web_url: https://en.wikipedia.org/wiki/Artificial_intelligence
    image_url: https://static.vecteezy.com/system/resources/thumbnails/036/105/045/small_2x/artificial-intelligence-ai-processor-chip-icon-symbol-for-graphic-design-logo-web-site-social-media-png.png
  
  

#topics:
#  - name: DevOps
#    web_url: https://www.redhat.com/en/topics/devops
#    image_url: https://devopedia.org/images/article/54/7602.1513404277.png
  
#  - name: Software Engineering
#    web_url: https://www.guru99.com/what-is-software-engineering.html
#    image_url: https://www.guru99.com/images/1/093019_0641_WhatisSoftw1.png
  
#    - name: Machine and Deep Learning
#    web_url: https://github.com/topics/machine-learning
#    image_url: https://cdn.pixabay.com/photo/2017/09/08/19/07/a-2729794_1280.png

#tolearn:
#  - name: Project Management
#    web_url: https://github.com/topics/project-management
#    image_url: https://cdn.pixabay.com/photo/2017/02/13/02/17/project-management-2061635_1280.jpg
  
#  - name: Amazon Web Services
#    web_url: https://github.com/topics/aws
#    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
      
#  - name: Unity
#    web_url: https://github.com/topics/unity
#    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/unity/unity.png
  
